# Generated by Django 5.0.4 on 2024-04-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_users_date_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=100000)),
                ('password', models.CharField(max_length=100000)),
                ('role', models.CharField(max_length=1000)),
                ('grade', models.CharField(max_length=1000)),
                ('school', models.CharField(max_length=100000)),
                ('state', models.CharField(max_length=100000)),
                ('city', models.CharField(max_length=100000)),
                ('country', models.CharField(max_length=100000)),
                ('date', models.DateField(default='2024-04-14')),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='city',
        ),
        migrations.RemoveField(
            model_name='users',
            name='country',
        ),
        migrations.RemoveField(
            model_name='users',
            name='date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.RemoveField(
            model_name='users',
            name='school',
        ),
        migrations.RemoveField(
            model_name='users',
            name='state',
        ),
    ]
