# Generated by Django 5.0.4 on 2024-04-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_students_remove_users_city_remove_users_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='role',
        ),
    ]
